# Generated by Django 2.0.4 on 2018-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='residual',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
