# Generated by Django 2.0.4 on 2018-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_maxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='maxi',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
