# Generated by Django 2.0.4 on 2018-05-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180516_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='maxi',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
