# Generated by Django 2.0.4 on 2018-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180516_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='maxi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='residual',
            field=models.IntegerField(default=100000),
        ),
    ]
