# Generated by Django 2.0.4 on 2018-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180516_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='maxi',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
