# Generated by Django 2.0.4 on 2018-05-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180516_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='maxi',
            new_name='assigned',
        ),
    ]
