# Generated by Django 2.0.4 on 2018-05-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180516_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='residual',
        ),
    ]
