# Generated by Django 2.0.4 on 2018-05-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_category_residual'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='written_date',
            field=models.DateField(auto_now=True),
        ),
    ]
