# Generated by Django 2.0.4 on 2018-05-17 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_history_written_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='written_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
