# Generated by Django 2.0.4 on 2018-05-29 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_history_halbu_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalbuHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_week_date', models.DateField(default=datetime.date(2018, 6, 5))),
                ('last_week_date', models.DateField(default=datetime.date(2018, 6, 5))),
                ('depre', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category')),
                ('history', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.History')),
            ],
        ),
    ]
