# Generated by Django 2.0.4 on 2018-05-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_halbuhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='halbu_week',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
