# Generated by Django 2.0.4 on 2018-06-11 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180529_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halbuhistory',
            name='last_week_date',
            field=models.DateField(default=datetime.date(2018, 6, 18)),
        ),
        migrations.AlterField(
            model_name='halbuhistory',
            name='second_week_date',
            field=models.DateField(default=datetime.date(2018, 6, 18)),
        ),
    ]
